version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGODB_HOST=db

  db:
    image: mongo:5.0.23
    ports:
      - 27017:27017
